### ISSUE TITLE
Matches reported at impossible times

### ISSUE THREAD

**Issue by Zehra** [allejo/bzion#141]
It seems it is possible to report two matches having happened at the exact same time and server port.
This seems to happen when a match is entered with the same time and place from another match.

**Comment by allejo** [comment]
Unlikely to ever happen, but does this cause any issues on the website itself?

**Comment by Zehra** [comment]
It does not appear to cause any issues, but perhaps might mess with scoring.

**Comment by allejo** [comment]
By nature, entering matches in the correct order is a necessity because that's how Elo works. Elo doesn't care about the exact timestamp or location of a match, just the order of the matches (whichever was entered first). If there's a bug with Elo recalculation, then that should be addressed in a separate issue but for now, entering two matches at the same time/place shouldn't be a cause for concern
