### ISSUE TITLE
Make sure that the port doesn't show up twice in match view pages

### ISSUE THREAD

**Issue by kongr45gpen** [allejo/bzion#61]
![example.com:5155:5155](https://cloud.githubusercontent.com/assets/720678/19455644/75778e0a-94c6-11e6-8c8e-039959fbb836.png)

**Comment by allejo** [comment]
League Overseer uses [bz_getPublicAddr()](https://wiki.bzflag.org/Bz_getPublicAddr) which reports `server:port` so that's what's being stored in the database.

**Possible Solutions**

1. Just use what's stored in the database and not include the port in the Twig solution.
1.  API controller can split up the `server:port` from the POST request and save the respective information; a database migration will probably be necessary to retroactively correct current matches.
    - This will be required to be ported to 1.0 with the API rewrite

**Comment by kongr45gpen** [comment]
> Just use what's stored in the database and not include the port in the Twig solution.

This seems more like a temporary workaround, and I'd prefer to have the API controller parse the POST data and store it properly.

Actually, would it make sense to store `address:port` in the database as one column, or split the address and port into two separate ones?

**Comment by allejo** [comment]
There was a [migration here](https://github.com/allejo/bzion/blob/be4aeee6c5d6f2fa846f6c2734b601bef6c2242b/migrations/20150902151315_split_server_address.php) to split it up into two columns but seems like I forgot to update the API controller to split it up as well, so it'd be safe to drop the port column entirely with no data loss. Also seems like the `servers` table stores this info together, we could possibly use this as a foreign key to match Match objects with Server objects?

**Comment by allejo** [comment]
Fixed in both 0.9.x and 1.0-dev. I'll close this for now, we can revisit this if needed for 1.0-dev
