### ISSUE TITLE
Use custom authentication that doesn't rely on BZFlag

### ISSUE THREAD

**Issue by MrMorcego** [allejo/bzion#66]
I would like to know which pass by default is coming.

I used the automatic installation, where the username appeared I chose "mrmorcego", when I ask for login and I enter the user and since you did not ask me for the password, I click on login and the error says the user name or password is Wrong, how can I fix this?

**Comment by allejo** [comment]
BZiON's login and authentication is tied directly to the [BZFlag forums](https://forums.bzflag.org/), as that's what this project was created for; the project can be modified to use its own login system instead of relying on a third-party login. BZiON itself doesn't store any passwords or login details other than the player's username and unique ID retrieved from the forums.

If I'm not mistaken, during the installation when it asks for your username, it is referring to the `bzion.miscellaneous.admin` field from the `app/config.yml` file, which is used to automatically grant admin permissions to the person installing BZiON, it's not actually creating a username/password combination.

What are you looking at doing with BZiON?

**Comment by MrMorcego** [comment]
How can I modify them so that they can register and log in without using the project forum?

**Comment by allejo** [comment]
There's no built-in switch for you to use to enable other authentication forms. You'd have to dive into BZiON and modify it to have actual authentication functionality and store hashed passwords or modify it to use another authentication that's not our project forum (you're gonna need some PHP experience). @kongr45gpen would probably be able to give a better description but I'm seeing two options here.

**1. Build an authentication system into BZiON**

- Create the appropriate views for login and registration in the [`views`](https://github.com/allejo/bzion/tree/81553fe1f992e9372e51226d29930ab894cc0d43/views) folder
- Tie those new views to controllers (new ones that you'll have to create) in [`app/routes.yml`](https://github.com/allejo/bzion/blob/81553fe1f992e9372e51226d29930ab894cc0d43/app/routes.yml)
- The [login controller](https://github.com/allejo/bzion/blob/81553fe1f992e9372e51226d29930ab894cc0d43/controllers/LoginController.php#L22-L38) would need to be stripped of the current logic that handles our forum login information and use your own authentication logic instead
- Modify the `players` table in the database to store the hashed passwords

**2. Use a third-party authentication system**

- Modify the [login controller](https://github.com/allejo/bzion/blob/81553fe1f992e9372e51226d29930ab894cc0d43/controllers/LoginController.php#L22-L38) to validate the information returned from your own external authentication system.

---

What are you looking at using BZiON for? Is it another gaming community/project? If BZiON is generic enough to suit the needs of other projects, I don't see why we can't consider incorporating a more modular/generic authentication setup or better documentation for different services to be used for auth.

**Comment by MrMorcego** [comment]
This is just for a tournament we Will have in a lan party. This Will be a offline access thats why i need to change the register and login.

Thank you for your attention. And good work on the project!
Best regards
